FROM python:3.8.18

ADD ./src /vflair
ADD ./requirements.txt /vflair/requirements.txt

WORKDIR /vflair
RUN pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

ENV PYTHONPATH "${PYTHONPATH}:/vflair"
EXPOSE 3333
CMD ["python", "./framework/server/grpc_server.py", "--config=./framework/server/server_config.yml"]