batch_size = 1
num_class  = 10
data_size = [batch_size, 3, 32, 32]
label_size = [batch_size, num_class]
dataset = 'CIAFR/'
verbose = 1
save_path = '/home/DAIR/duzx/FedGen/attacks/' + dataset
save_per_iter = 10
device = "cuda:0"
amplify_magnitude = 1000
