# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: framework/protos/message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from framework.protos import node_pb2 as framework_dot_protos_dot_node__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66ramework/protos/message.proto\x12\x10\x66ramework.protos\x1a\x1b\x66ramework/protos/node.proto\"\xc5\x01\n\x07Message\x12$\n\x04node\x18\x01 \x01(\x0b\x32\x16.framework.protos.Node\x12$\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x16.framework.protos.Code\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\".framework.protos.AggregationValue\x12+\n\x04type\x18\x05 \x01(\x0e\x32\x1d.framework.protos.MessageType\"g\n\x05Value\x12\x10\n\x06\x64ouble\x18\x01 \x01(\x01H\x00\x12\x10\n\x06sint64\x18\x02 \x01(\x12H\x00\x12\x0e\n\x04\x62ool\x18\x03 \x01(\x08H\x00\x12\x10\n\x06string\x18\x04 \x01(\tH\x00\x12\x0f\n\x05\x62ytes\x18\x05 \x01(\x0cH\x00\x42\x07\n\x05value\"\xaa\x01\n\x10\x41ggregationValue\x12I\n\x0cnamed_values\x18\x01 \x03(\x0b\x32\x33.framework.protos.AggregationValue.NamedValuesEntry\x1aK\n\x10NamedValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.framework.protos.Value:\x02\x38\x01*\x19\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01*h\n\x0bMessageType\x12\t\n\x05PLAIN\x10\x00\x12\x0e\n\nCREATE_JOB\x10\x01\x12\r\n\tQUERY_JOB\x10\x02\x12\x0f\n\x0b\x46INISH_TASK\x10\x03\x12\x0e\n\nSTART_TASK\x10\x04\x12\x0e\n\nUNREGISTER\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'framework.protos.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGGREGATIONVALUE_NAMEDVALUESENTRY']._options = None
  _globals['_AGGREGATIONVALUE_NAMEDVALUESENTRY']._serialized_options = b'8\001'
  _globals['_CODE']._serialized_start=559
  _globals['_CODE']._serialized_end=584
  _globals['_MESSAGETYPE']._serialized_start=586
  _globals['_MESSAGETYPE']._serialized_end=690
  _globals['_MESSAGE']._serialized_start=82
  _globals['_MESSAGE']._serialized_end=279
  _globals['_VALUE']._serialized_start=281
  _globals['_VALUE']._serialized_end=384
  _globals['_AGGREGATIONVALUE']._serialized_start=387
  _globals['_AGGREGATIONVALUE']._serialized_end=557
  _globals['_AGGREGATIONVALUE_NAMEDVALUESENTRY']._serialized_start=482
  _globals['_AGGREGATIONVALUE_NAMEDVALUESENTRY']._serialized_end=557
# @@protoc_insertion_point(module_scope)
